//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EstructuraProyecto2.0.rc
//
#define IDD_INICIARSESION               101
#define IDR_MENU1                       103
#define IDD_REGISTRARSE                 104
#define IDD_REGISTROPERSONAS            106
#define IDD_REGISTROVACUNAS             108
#define INICIARSESION_USUARIO           1001
#define INICIARSESION_CONTR             1002
#define BTN_REGISTRARSE_REGISTRO        1003
#define BTN_REGISTRO_USUARIO            1006
#define BTN_REGISTRO_CONTRA             1007
#define BTN_INIC_INICIARSESION          1007
#define BTN_REGISTRO_NOMBRES            1008
#define BTN_INIC_REGISTRARSE            1008
#define BTN_REGISTRO_APPATERNO          1009
#define IDC_REGISTROPERSONAS_REGISTRARBTN 1009
#define BTN_REGISTRO_APMATERNO          1010
#define IDC_REGISTROPERSONAS_CARGARFOTOBTN 1010
#define IDC_REGISTROPERSONAS_PATERNO    1011
#define IDC_REGISTROPERSONAS_SEXO       1012
#define IDC_REGISTROPERSONAS_GRUPOOCUPA 1013
#define IDC_REGISTROPERSONAS_MATERNO    1014
#define IDC_REGISTROPERSONAS_NOMBRES    1015
#define IDC_REGISTROPERSONAS_CURP       1016
#define IDC_REGISTROPERSONAS_RFC        1017
#define IDC_REGISTROPERSONAS_DATEPICK   1018
#define IDC_REGISTROPERSONAS_COLONIA    1019
#define IDC_REGISTROPERSONAS_CIUDAD     1020
#define IDC_REGISTROPERSONAS_CALLE      1021
#define IDC_REGISTROPERSONAS_ESTADO     1022
#define IDC_REGISTROPERSONAS_ESTADOCIVIL 1023
#define IDC_REGISTROPERSONAS_TELEFONO   1024
#define IDC_REGISTROPERSONAS_PRETELEFONO 1025
#define IDC_REGISTROPERSONAS_FOTO       1026
#define IDC_REGISTROPERSONAS_PERFILRIESGO 1027
#define BTN_REGISTROVACUNAS_REGISTRAR   1027
#define IDC_REGISTRARVACUNA_TIPO        1028
#define IDC_REGISTRARVACUNA_MARCA       1029
#define IDC_REGISTRARVACUNA_NODOSIS     1030
#define IDC_REGISTRARVACUNA_CLAVE       1031
#define IDC_REGISTRARVACUNA_DESCRIPCION 1032
#define IDC_REGISTRARVACUNA_PRECIO      1033
#define ID_REGISTRAR_PERSONAS           40001
#define ID_REGISTRAR_VACUNAS            40002
#define ID_REGISTRO_PERSONAS            40003
#define ID_REGISTRO_VACUNAS             40004
#define ID_SALIR_SALIR                  40005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40006
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
